[project]
name = "pipeline-ci-cd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.2",
    "mkdocs>=1.6.1",
    "mlflow>=3.6.0",
    "pandas>=2.3.3",
    "ruff>=0.14.5",
    "scikit-learn>=1.7.2",
]
